r_tc_user:
    resource: "@rTCUserBundle/Resources/config/routing.yml"
    prefix:   /

r_tc:
    resource: "@rTCBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
